# Generated by Django 4.1.7 on 2023-04-04 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movingticket',
            options={'ordering': ['ticket', 'created_at'], 'verbose_name': 'Движение билета', 'verbose_name_plural': 'Движения билетов'},
        ),
        migrations.AlterField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_session', to='movie.movie', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_session', to='movie.room', verbose_name='Зал'),
        ),
    ]
