# Generated by Django 4.1.7 on 2023-04-11 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0003_alter_movie_options_movie_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movingticket',
            name='employee',
        ),
        migrations.AddField(
            model_name='movingticket',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
            preserve_default=False,
        ),
    ]
